language: objective-c  #1
osx_image: xcode10.3 #2
xcode_project: demo.xcodeproj #3
xcode_scheme: demo #4 
xcode_sdk: iphonesimulator12.4 #5

jobs:
  include:
   # - stage: Swiflint
     # script:
     #   - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - fastlane scan -s demoTest

    - stage: XCTest
      script:
        - fastlane scan -s demoUITest
env:
  global:
  - APPNAME="3Embed Demo App"
  - 'DEVELOPER_NAME="iPhone Distribution: KEYUR PATEL (CODE)"'
  - PROFILE_UUID=89a43100-3c2f-4259-ad4e-a1c241f719dc
